prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
  service:
    type: NodePort

grafana:
  sidecar:
    datasources:
      defaultDatasourceEnabled: true
  additionalDataSources:
    - name: Loki
      type: loki
      # Use the internal Kubernetes service name for Loki
      url: http://loki-loki-distributed-query-frontend.monitoring:3100
  service:
    type: NodePort