Vagrant.configure("2") do |config|
  # Base box
  config.vm.box = "ubuntu/jammy64"

  # Kubernetes Masters
  (1..2).each do |i|
    config.vm.define "master#{i}" do |node|
      node.vm.hostname = "master#{i}"
      node.vm.network "public_network", bridge: "Intel(R) Wi-Fi 6 AX201 160MHz"

      node.vm.network "private_network", ip: "192.168.56.1#{i}"


      node.vm.provider "virtualbox" do |vb|
        vb.name = "k8smaster#{i}"
        vb.cpus = 2
        vb.memory = 2048
      end

      if Vagrant.has_plugin?("vagrant-disksize")
        node.disksize.size = "20GB"
      end

      # Common setup script for all masters
      node.vm.provision "K8sDocker", type: "shell", path: "automate.sh"

      # Run kubeadm init only on master1
      if i == 1
        node.vm.provision "KubeInit", type: "shell", path: "ClusterInit.sh",
          env: { "LOADBALANCER_IP" => "192.168.1.100" }
      end
    end
  end

  # Kubernetes Workers
  (1..2).each do |i|
    config.vm.define "worker#{i}" do |node|
      node.vm.hostname = "worker#{i}"
      node.vm.network "public_network", bridge: "Intel(R) Wi-Fi 6 AX201 160MHz"

      node.vm.network "private_network", ip: "192.168.56.2#{i}"
      node.vm.provider "virtualbox" do |vb|
        vb.name = "k8sworker#{i}"
        vb.cpus = 2
        vb.memory = 3072
      end

      if Vagrant.has_plugin?("vagrant-disksize")
        node.disksize.size = "20GB"
      end

      node.vm.provision "K8sDocker", type: "shell", path: "automate.sh"
    end
  end

  # Load Balancer
  config.vm.define "loadbalancer" do |node|
    node.vm.hostname = "loadbalancer"
    node.vm.network "public_network", ip: "192.168.1.100", bridge: "Intel(R) Wi-Fi 6 AX201 160MHz"

    node.vm.provider "virtualbox" do |vb|
      vb.name = "k8s-loadbalancer"
      vb.cpus = 1
      vb.memory = 1024
    end

    if Vagrant.has_plugin?("vagrant-disksize")
      node.disksize.size = "10GB"
    end

    node.vm.provision "HaProxy", type: "shell", path: "lb-provision.sh"
  end
end
