version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '${MYSQLDB_DOCKER_PORT}:${MYSQLDB_LOCAL_PORT}'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  springapp:
    build: .
    image: spring-springapp:latest
    container_name: springapp
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '${SPRING_DOCKER_PORT}:${SPRING_LOCAL_PORT}'

    environment:
      SPRING_APPLICATION_JSON: '{
        "server.port": "${SPRING_LOCAL_PORT}",
        "spring.datasource.url": "${SPRING_DOCKER_DATASOURCE_URL}",
        "spring.datasource.username" : "${MYSQL_USER}",
        "spring.datasource.password" : "${MYSQL_PASSWORD}"
        }'

